version: "3.3"

services:
  # MySQL
  db:
    container_name: "dbforget"
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password 
      MYSQL_ROOT_PASSWORD: password 
    ports:
      - "3306:3307"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d 
      - ./docker/mysql/conf.d:/etc/mysql/conf.d 
      - ./log/mysql:/var/log/mysql 
    networks:
      - local-net

  # FastAPI
  api:
    links:
      - dbforget
    container_name: "apiforget"
    build: ./docker/api
    ports:
      - "8000:6050"
    volumes:
      - ./code:/usr/src/server
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
